- name: Analyze bundle sizes
  uses: transferwise/actions-next-bundle-analyzer@master
  with:
    workflow-id: bundle-size.yml
    base-branch: main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
