schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: 1304c69562e74449e19115f1191c16
documents:
  - ./src/**/*.graphql
config:
  namingConvention:
    enumValues: 'change-case-all#upperCaseFirst'
generates:
  src/graphql/types.gen.ts:
    plugins:
      - typescript
      - typescript-operations:
          globalNamespace: true
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
  src/graphql/sdk.gen.ts:
    plugins:
      - typescript-graphql-request
hooks:
  afterAllFileWrite: 'prettier --write'
